FEATURE_GROUPS = {
    "user_velocity": [
        "user_txn_count_1min",
        "user_txn_count_5min",
        "user_txn_count_1hr",
        "user_txn_count_24hr",
        "user_txn_count_7d",
        "user_amount_sum_1hr",
        "user_amount_sum_24hr",
        "user_distinct_merchants_1hr",
        "user_distinct_merchants_24hr",
        "user_distinct_countries_24hr",
    ],
    "user_history": [
        "user_avg_txn_amount_30d",
        "user_std_txn_amount_30d",
        "user_max_txn_amount_30d",
        "user_preferred_merchant_categories",
        "user_typical_txn_hour",
        "user_typical_txn_day_of_week",
        "user_account_age_days",
        "user_total_lifetime_txns",
    ],
    "transaction": [
        "amount",
        "amount_log",
        "amount_zscore_vs_user_avg",
        "is_round_amount",
        "is_card_present",
        "channel_encoded",
        "merchant_category_encoded",
        "hour_of_day",
        "day_of_week",
        "is_weekend",
        "is_night",
    ],
    "geo": [
        "distance_from_home",
        "distance_from_last_txn",
        "time_since_last_txn_hours",
        "impossible_travel",
        "speed_km_per_hour",
        "country_change",
        "is_high_risk_country",
    ],
    "merchant": [
        "merchant_fraud_rate_30d",
        "merchant_txn_count_30d",
        "is_new_merchant_for_user",
        "merchant_category_risk_score",
        "merchant_avg_txn_amount",
    ],
    "device": [
        "is_new_device",
        "device_fraud_rate",
        "is_vpn_or_proxy",
        "ip_country_mismatch",
        "is_emulator",
    ],
    "network": [
        "shared_device_fraud_connections",
        "shared_ip_fraud_connections",
        "merchant_ip_risk_score",
    ],
}
